### ISSUE TITLE
New Homepage

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/vr.lullabot.com#10]
vr.lullabot.com is currently the place to go for a single experience that was designed for drupalcon 2016.

The goal is to make it more useful than that. It should be a 
* static single page that leads directly into any other experiences we create
* have a list of articles that we write on the topic from lullabot.com/topics/vr

Design:
* https://projects.invisionapp.com/d/main#/console/10298191/228931747/inspect

Possible experiences:
* we should move the current one into it's own folder and have a link to it (team photo)
* expanse (subdir)
* gallery (subdir)
* inside (subdir)
* videovr (give this it's own page and then a link to the exp from there)
  * design: https://projects.invisionapp.com/d/main#/console/10298191/229002635/inspect
* AR lullabot

## Tasks
- [x] recreate lullabot.com/vr in static html
- [x] add a 360° header
- [x] highlight articles and/or pull in a feed from lullabot.com/topics/vr
- [x] responsive design for mobile
- [x] add more projects
- [ ] redirect lullabot.com/vr to vr.lullabot.com (metatag should suffice)

**Comment by sirkitree** [comment]
We currently have lullabot.com/vr as well, which is a bit difficult to change at the moment. I'd like to redirect this to vr.lullabot.com and control this from this repo instead.

[ ] redirect lullabot.com/vr to vr.lullabot.com (metatag should suffice)
[ ] add a 360° header
[ ] add more projects
[ ] highlight articles and/or pull in a feed from lullabot.com/topics/vr

## 360° header
I'd like the header to be an embedded vr view. A similar site that I'm looking to replicate the effect of for this embed: https://geildanke.com/GEILDANKE/en/vr/

We should be able to use this: https://developers.google.com/vr/concepts/vrview-web
360° photo: https://cdn.rawgit.com/Lullabot/vr.lullabot.com/gh-pages/team-photo/assets/team.jpg

**Comment by davexoxide** [comment]
@sirkitree Do you want me to pull in the current page as the `index.html` of this repository or would it be okay to make it a sub-folder w/ it's own `index.html`

**Comment by sirkitree** [comment]
the existing one just redirects to lullabot.com/vr so I think it's fine to remove it.

**Comment by davexoxide** [comment]
@sirkitree I'll have some time to work on this. What are the remaining task?

* Add more links to featured demos?
* x-browser/x-device testing?

**Comment by sirkitree** [comment]
Yea, possibly better responsive styles so it at least looks ok on a phone (right now it looks drastically broken on mobile).

I'll update the original description with a list of tasks.

**Comment by sirkitree** [comment]
Latest commits to the branch now have responsive styles, utilizing more bootstrap classes and removing much of the custom css.
